backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "artikelen"
    label: "Artikelen"
    folder: "content/artikelen"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Publicatiedatum", name: "date", widget: "datetime"}
      - {label: "Kopfoto", name: "featured_image", widget: "image", required: false}
      - {label: "Korte Samenvatting", name: "summary", widget: "text"}
      - {label: "Inhoud", name: "body", widget: "markdown"}

  - name: "enquetes"
    label: "Enquêtes"
    folder: "content/enquetes"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Publicatiedatum", name: "date", widget: "datetime"}
      - {label: "Kopfoto", name: "featured_image", widget: "image", required: false}
      - {label: "Directe Enquête Link (bijv. Google Forms)", name: "survey_link", widget: "string", required: false}
      - {label: "Korte Samenvatting", name: "summary", widget: "text"}
      - {label: "Toelichting / Inhoud", name: "body", widget: "markdown"}
